### ISSUE TITLE
All but 2 tests are broken on alpha branch

### ISSUE THREAD

**Issue by poiyomi** [ChrisAlderson/nyaa-api-pt#2]
`  NyaaApi
    1) should get a torrent
    2) should get a torrent head
    √ should upload a torrent
    √ should update a torrent
    3) should search for torrents with sort as a string
    4) should search for torrents without parameters
    5) should login with a username and password
    6) should get a profile by the id
    7) should refresh the api token
    8) should check the api token

  2 passing (33ms)
  8 failing

  1) NyaaApi should get a torrent:
     Uncaught Error: "value" required in setHeader("authorization", value)
      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
      at new ClientRequest (_http_client.js:85:14)
      at Object.exports.request (http.js:31:10)
      at Object.exports.request (https.js:202:15)
      at get (node_modules\got\index.js:49:18)
      at Immediate.setImmediate (node_modules\got\index.js:124:3)

  2) NyaaApi should get a torrent head:
     Uncaught Error: "value" required in setHeader("authorization", value)
      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
      at new ClientRequest (_http_client.js:85:14)
      at Object.exports.request (http.js:31:10)
      at Object.exports.request (https.js:202:15)
      at get (node_modules\got\index.js:49:18)
      at Immediate.setImmediate (node_modules\got\index.js:124:3)

  3) NyaaApi should search for torrents with sort as a string:
     Uncaught Error: "value" required in setHeader("authorization", value)
      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
      at new ClientRequest (_http_client.js:85:14)
      at Object.exports.request (http.js:31:10)
      at Object.exports.request (https.js:202:15)
      at get (node_modules\got\index.js:49:18)
      at Immediate.setImmediate (node_modules\got\index.js:124:3)

  4) NyaaApi should search for torrents without parameters:
     Uncaught Error: "value" required in setHeader("authorization", value)
      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
      at new ClientRequest (_http_client.js:85:14)
      at Object.exports.request (http.js:31:10)
      at Object.exports.request (https.js:202:15)
      at get (node_modules\got\index.js:49:18)
      at Immediate.setImmediate (node_modules\got\index.js:124:3)

  5) NyaaApi should login with a username and password:
     Uncaught Error: "value" required in setHeader("authorization", value)
      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
      at new ClientRequest (_http_client.js:85:14)
      at Object.exports.request (http.js:31:10)
      at Object.exports.request (https.js:202:15)
      at get (node_modules\got\index.js:49:18)
      at Immediate.setImmediate (node_modules\got\index.js:124:3)

  6) NyaaApi should get a profile by the id:
     Uncaught Error: "value" required in setHeader("authorization", value)
      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
      at new ClientRequest (_http_client.js:85:14)
      at Object.exports.request (http.js:31:10)
      at Object.exports.request (https.js:202:15)
      at get (node_modules\got\index.js:49:18)
      at Immediate.setImmediate (node_modules\got\index.js:124:3)

  7) NyaaApi should refresh the api token:
     Uncaught Error: "value" required in setHeader("authorization", value)
      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
      at new ClientRequest (_http_client.js:85:14)
      at Object.exports.request (http.js:31:10)
      at Object.exports.request (https.js:202:15)
      at get (node_modules\got\index.js:49:18)
      at Immediate.setImmediate (node_modules\got\index.js:124:3)

  8) NyaaApi should check the api token:
     Uncaught Error: "value" required in setHeader("authorization", value)
      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
      at new ClientRequest (_http_client.js:85:14)
      at Object.exports.request (http.js:31:10)
      at Object.exports.request (https.js:202:15)
      at get (node_modules\got\index.js:49:18)
      at Immediate.setImmediate (node_modules\got\index.js:124:3)

----------------|----------|----------|----------|----------|----------------|
File            |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------|----------|----------|----------|----------|----------------|
All files       |    85.19 |      100 |       75 |    85.19 |                |
 nyaa-api-pt.js |    85.19 |      100 |       75 |    85.19 |147,191,243,286 |
----------------|----------|----------|----------|----------|----------------|
npm ERR! Test failed.  See above for more details.`

**Comment by ChrisAlderson** [comment]
Have you set the `NYAA_USER`, `NYAA_PASS` and `NYAA_TOKEN` environment variables?

Some of the api methods need it in order to work.

**Comment by poiyomi** [comment]
oh, of course. My bad. I just assumed it didn't require any authentication.

**Comment by ChrisAlderson** [comment]
Don't worry, I haven't done any documentation for the `2.0.0-alpha` branch. So I understand it's a bit confusing.
